import type { Template } from '../types';

// 微信公众号模板 - 按使用场景分类
export const wechatTemplates: Template[] = [
  {
    id: 'wechat-tech',
    name: '技术文章',
    format: 'wechat',
    description: '适合技术博客、代码教程',
    themeColors: ['#24292e', '#0366d6', '#f6f8fa'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.8; color: #24292e;',
      h1: 'font-size: 1.6em; font-weight: 600; margin: 1.2em 0 0.8em; color: #24292e; padding-bottom: 0.4em; border-bottom: 2px solid #eaecef;',
      h2: 'font-size: 1.4em; font-weight: 600; margin: 1em 0 0.6em; color: #24292e; border-bottom: 1px solid #eaecef; padding-bottom: 0.3em;',
      h3: 'font-size: 1.2em; font-weight: 600; margin: 0.8em 0 0.5em; color: #24292e;',
      p: 'margin: 0.8em 0; text-align: justify; color: #24292e;',
      blockquote: 'border-left: 4px solid #dfe2e5; padding: 0.6em 1em; margin: 1em 0; background: #f6f8fa; color: #6a737d;',
      code: 'background: rgba(27,31,35,0.05); padding: 2px 6px; border-radius: 3px; font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace; font-size: 0.9em; color: #d73a49;',
      pre: 'background: #f6f8fa; color: #24292e; padding: 1em; border-radius: 6px; overflow-x: auto; margin: 1em 0; border: 1px solid #eaecef;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.3em 0;',
      img: 'max-width: 100%; height: auto; border-radius: 4px; margin: 0.8em 0; border: 1px solid #eaecef;',
      a: 'color: #0366d6; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #f6f8fa; padding: 0.6em 0.8em; border: 1px solid #dfe2e5; text-align: left; font-weight: 600;',
      td: 'padding: 0.6em 0.8em; border: 1px solid #dfe2e5;',
      hr: 'border: none; height: 2px; background: linear-gradient(to right, transparent, #eaecef, transparent); margin: 1.5em 0;',
    },
  },
  {
    id: 'wechat-story',
    name: '情感故事',
    format: 'wechat',
    description: '适合散文、故事、情感类文章',
    themeColors: ['#5d4e37', '#8b7355', '#faf8f5'],
    styles: {
      container: 'max-width: 100%; padding: 24px 20px; line-height: 2; color: #3e3e3e; font-family: Georgia, "Noto Serif SC", serif;',
      h1: 'font-size: 1.5em; font-weight: normal; margin: 1.2em 0 0.8em; color: #5d4e37; text-align: center; letter-spacing: 2px; padding-bottom: 0.5em; border-bottom: 1px dashed #d4c4b0;',
      h2: 'font-size: 1.3em; font-weight: normal; margin: 1em 0 0.6em; color: #5d4e37; text-align: center; padding-bottom: 0.3em; border-bottom: 1px dotted #d4c4b0;',
      h3: 'font-size: 1.1em; font-weight: normal; margin: 0.8em 0 0.5em; color: #8b7355;',
      p: 'margin: 1em 0; text-align: justify; text-indent: 2em; color: #3e3e3e;',
      blockquote: 'border: none; padding: 1em 1.5em; margin: 1.5em 0; background: #faf8f5; color: #8b7355; text-align: center; font-style: italic;',
      code: 'background: #faf8f5; padding: 2px 6px; border-radius: 2px; font-size: 0.9em; color: #8b7355;',
      pre: 'background: #faf8f5; color: #5d4e37; padding: 1em; border-radius: 4px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.3em 0; line-height: 1.8;',
      img: 'max-width: 100%; height: auto; border-radius: 8px; margin: 1.5em auto; display: block;',
      a: 'color: #8b7355; text-decoration: underline; text-decoration-color: #d4c4b0;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #faf8f5; padding: 0.6em; border: 1px solid #e8e0d5; text-align: left; color: #5d4e37;',
      td: 'padding: 0.6em; border: 1px solid #e8e0d5;',
      hr: 'border: none; height: 1px; background: linear-gradient(to right, transparent, #d4c4b0, #d4c4b0, transparent); margin: 2em 0;',
    },
  },
  {
    id: 'wechat-news',
    name: '新闻资讯',
    format: 'wechat',
    description: '适合新闻、公告、快讯',
    themeColors: ['#c00000', '#000000', '#f5f5f5'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.8; color: #333; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif;',
      h1: 'font-size: 1.5em; font-weight: bold; margin: 0 0 0.8em 0; color: #000; line-height: 1.4; padding-bottom: 0.4em; border-bottom: 3px solid #c00000;',
      h2: 'font-size: 1.2em; font-weight: bold; margin: 1em 0 0.5em 0; color: #333; border-left: 4px solid #c00000; padding-left: 0.8em;',
      h3: 'font-size: 1.1em; font-weight: bold; margin: 0.8em 0 0.4em 0; color: #333;',
      p: 'margin: 0.8em 0; text-align: justify; text-indent: 2em;',
      blockquote: 'border-left: 4px solid #c00000; padding: 0.6em 1em; margin: 1em 0; background: #fff5f5; color: #666; font-style: normal;',
      code: 'background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; color: #c00000;',
      pre: 'background: #f5f5f5; color: #333; padding: 1em; border-radius: 4px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.3em 0;',
      img: 'max-width: 100%; height: auto; margin: 0.8em 0;',
      a: 'color: #c00000; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #f5f5f5; color: #333; padding: 0.6em; border: 1px solid #c00000; text-align: left;',
      td: 'padding: 0.6em; border: 1px solid #ddd;',
      hr: 'border: none; height: 1px; background: #c00000; margin: 1.5em 0; opacity: 0.3;',
    },
  },
  {
    id: 'wechat-product',
    name: '产品介绍',
    format: 'wechat',
    description: '适合产品发布、功能介绍',
    themeColors: ['#1677ff', '#0958d9', '#e6f4ff'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.8; color: #333;',
      h1: 'font-size: 1.6em; font-weight: 600; margin: 0 0 0.8em 0; color: #000; text-align: center; padding-bottom: 0.5em; border-bottom: 3px solid #1677ff;',
      h2: 'font-size: 1.3em; font-weight: 600; margin: 1.2em 0 0.6em 0; color: #0958d9; padding-bottom: 0.3em; border-bottom: 2px solid #91caff;',
      h3: 'font-size: 1.1em; font-weight: 600; margin: 0.8em 0 0.4em 0; color: #1677ff;',
      p: 'margin: 0.8em 0; text-align: justify;',
      blockquote: 'border: none; padding: 1em 1.2em; margin: 1em 0; background: linear-gradient(135deg, #e6f4ff 0%, #f0f5ff 100%); color: #0958d9; border-radius: 8px;',
      code: 'background: #e6f4ff; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #0958d9;',
      pre: 'background: #1a1a1a; color: #e6f4ff; padding: 1em; border-radius: 8px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.4em 0;',
      img: 'max-width: 100%; height: auto; border-radius: 12px; margin: 1em 0; box-shadow: 0 4px 12px rgba(0,0,0,0.1);',
      a: 'color: #1677ff; text-decoration: none; font-weight: 500;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0; border-radius: 8px; overflow: hidden;',
      th: 'background: #e6f4ff; color: #333; padding: 0.8em; text-align: left;',
      td: 'padding: 0.8em; border-bottom: 1px solid #e6f4ff;',
      hr: 'border: none; height: 2px; background: linear-gradient(to right, #1677ff, #91caff); margin: 1.5em 0; border-radius: 1px;',
    },
  },
  {
    id: 'wechat-tutorial',
    name: '教程指南',
    format: 'wechat',
    description: '适合操作教程、步骤说明',
    themeColors: ['#52c41a', '#389e0d', '#f6ffed'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.8; color: #333;',
      h1: 'font-size: 1.5em; font-weight: 600; margin: 0 0 0.8em 0; color: #389e0d; border-bottom: 3px solid #52c41a; padding-bottom: 0.4em;',
      h2: 'font-size: 1.3em; font-weight: 600; margin: 1.2em 0 0.6em 0; color: #389e0d; padding-bottom: 0.3em; border-bottom: 2px solid #b7eb8f;',
      h3: 'font-size: 1.1em; font-weight: 600; margin: 0.8em 0 0.4em 0; color: #52c41a;',
      p: 'margin: 0.8em 0; text-align: justify;',
      blockquote: 'border-left: 4px solid #52c41a; padding: 0.6em 1em; margin: 1em 0; background: #f6ffed; color: #389e0d;',
      code: 'background: #f6ffed; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #389e0d; font-family: Menlo, Monaco, monospace;',
      pre: 'background: #262626; color: #f6ffed; padding: 1em; border-radius: 8px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0; list-style: none;',
      ol: 'padding-left: 0; margin: 0.8em 0; list-style: none; counter-reset: ol-counter;',
      li: 'margin: 0.4em 0; position: relative;',
      img: 'max-width: 100%; height: auto; border-radius: 8px; margin: 1em 0; border: 1px solid #b7eb8f;',
      a: 'color: #52c41a; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #f6ffed; color: #333; padding: 0.6em; text-align: left;',
      td: 'padding: 0.6em; border-bottom: 1px solid #d9f7be;',
      hr: 'border: none; height: 2px; background: linear-gradient(to right, #52c41a, #b7eb8f, transparent); margin: 1.5em 0;',
    },
  },
  {
    id: 'wechat-business',
    name: '商务报告',
    format: 'wechat',
    description: '适合商业分析、工作汇报',
    themeColors: ['#2f54eb', '#1d39c4', '#f0f5ff'],
    styles: {
      container: 'max-width: 100%; padding: 24px 20px; line-height: 1.7; color: #333; font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif;',
      h1: 'font-size: 1.5em; font-weight: 600; margin: 0 0 0.8em 0; color: #1d39c4; text-align: center; letter-spacing: 1px; padding-bottom: 0.5em; border-bottom: 2px solid #2f54eb;',
      h2: 'font-size: 1.2em; font-weight: 600; margin: 1.2em 0 0.6em 0; color: #2f54eb; border-left: 4px solid #2f54eb; padding-left: 0.8em;',
      h3: 'font-size: 1em; font-weight: 600; margin: 0.8em 0 0.4em 0; color: #1d39c4;',
      p: 'margin: 0.6em 0; text-align: justify;',
      blockquote: 'border: none; padding: 0.8em 1.2em; margin: 1em 0; background: #f0f5ff; color: #1d39c4; border-radius: 4px;',
      code: 'background: #f0f5ff; padding: 2px 5px; border-radius: 3px; font-size: 0.9em; color: #2f54eb;',
      pre: 'background: #f0f5ff; color: #1d39c4; padding: 1em; border-radius: 4px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.6em 0;',
      ol: 'padding-left: 1.5em; margin: 0.6em 0;',
      li: 'margin: 0.3em 0;',
      img: 'max-width: 100%; height: auto; border-radius: 4px; margin: 0.8em 0;',
      a: 'color: #2f54eb; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #f0f5ff; color: #333; padding: 0.7em; text-align: left; font-size: 0.95em;',
      td: 'padding: 0.7em; border-bottom: 1px solid #d6e4ff; font-size: 0.95em;',
      hr: 'border: none; height: 1px; background: linear-gradient(to right, transparent, #2f54eb, transparent); margin: 1.5em 0;',
    },
  },
  {
    id: 'wechat-lifestyle',
    name: '生活分享',
    format: 'wechat',
    description: '适合日常分享、美食旅游',
    themeColors: ['#eb2f96', '#c41d7f', '#fff0f6'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.9; color: #333;',
      h1: 'font-size: 1.5em; font-weight: 500; margin: 0 0 0.8em 0; color: #c41d7f; text-align: center; padding-bottom: 0.5em; border-bottom: 2px dashed #eb2f96;',
      h2: 'font-size: 1.2em; font-weight: 500; margin: 1em 0 0.6em 0; color: #c41d7f; padding-bottom: 0.3em; border-bottom: 1px dotted #ffd6e7;',
      h3: 'font-size: 1.1em; font-weight: 500; margin: 0.8em 0 0.4em 0; color: #eb2f96;',
      p: 'margin: 0.8em 0; text-align: justify;',
      blockquote: 'border: none; padding: 1em 1.5em; margin: 1.2em 0; background: linear-gradient(to right, #fff0f6, #ffffff); color: #c41d7f; border-radius: 12px; text-align: center;',
      code: 'background: #fff0f6; padding: 2px 6px; border-radius: 10px; font-size: 0.9em; color: #c41d7f;',
      pre: 'background: #2d1f2f; color: #fff0f6; padding: 1em; border-radius: 12px; overflow-x: auto; margin: 1em 0;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.4em 0;',
      img: 'max-width: 100%; height: auto; border-radius: 16px; margin: 1em 0;',
      a: 'color: #eb2f96; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0; border-radius: 12px; overflow: hidden;',
      th: 'background: #fff0f6; color: #333; padding: 0.6em; text-align: left;',
      td: 'padding: 0.6em; border-bottom: 1px solid #ffd6e7;',
      hr: 'border: none; height: 2px; background: linear-gradient(to right, transparent, #eb2f96, #ffd6e7, #eb2f96, transparent); margin: 2em 0;',
    },
  },
  {
    id: 'wechat-dark',
    name: '暗夜模式',
    format: 'wechat',
    description: '护眼暗色主题，适合夜间阅读',
    themeColors: ['#1a1a1a', '#61afef', '#98c379'],
    styles: {
      container: 'max-width: 100%; padding: 20px; line-height: 1.8; color: #abb2bf; background: #282c34;',
      h1: 'font-size: 1.6em; font-weight: 600; margin: 1.2em 0 0.8em; color: #e06c75; border-bottom: 2px solid #3e4451; padding-bottom: 0.4em;',
      h2: 'font-size: 1.4em; font-weight: 600; margin: 1em 0 0.6em; color: #61afef; border-bottom: 1px solid #3e4451; padding-bottom: 0.3em;',
      h3: 'font-size: 1.2em; font-weight: 600; margin: 0.8em 0 0.5em; color: #98c379;',
      p: 'margin: 0.8em 0; text-align: justify; color: #abb2bf;',
      blockquote: 'border-left: 4px solid #3e4451; padding: 0.6em 1em; margin: 1em 0; background: #21252b; color: #5c6370;',
      code: 'background: #21252b; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #98c379; font-family: Menlo, Monaco, monospace;',
      pre: 'background: #21252b; color: #abb2bf; padding: 1em; border-radius: 8px; overflow-x: auto; margin: 1em 0; border: 1px solid #3e4451;',
      ul: 'padding-left: 1.5em; margin: 0.8em 0;',
      ol: 'padding-left: 1.5em; margin: 0.8em 0;',
      li: 'margin: 0.3em 0;',
      img: 'max-width: 100%; height: auto; border-radius: 8px; margin: 0.8em 0;',
      a: 'color: #61afef; text-decoration: none;',
      table: 'width: 100%; border-collapse: collapse; margin: 1em 0;',
      th: 'background: #21252b; padding: 0.6em; border: 1px solid #3e4451; text-align: left; color: #61afef;',
      td: 'padding: 0.6em; border: 1px solid #3e4451; color: #abb2bf;',
      hr: 'border: none; height: 1px; background: linear-gradient(to right, transparent, #3e4451, #61afef, #3e4451, transparent); margin: 1.5em 0;',
    },
  },
];
